version: "3.8"

services:
  testquantumdocs:
    build: .
    ports:
      - "5221:80"
    depends_on:
      - mysql
    environment:
     - ASPNETCORE_ENVIRONMENT=Development
     - ASPNETCORE_URLS=http://+:80
     - ConnectionStrings__DefaultConnection=server=mysql;port=3306;database=testdb;user=root;password=MyPassword123
    restart: unless-stopped


  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: MyPassword123
      MYSQL_DATABASE: testdb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data:
